# Generated by Django 2.2 on 2020-05-14 08:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_platfrom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='streaming_platfrom.Album'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.UUIDField(default=uuid.UUID('225c7746-7bc8-44a4-97e9-0b4583f143b7'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
