# Generated by Django 2.2 on 2020-05-14 08:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_platfrom', '0002_auto_20200514_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='streaming_platfrom.Album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.UUIDField(default=uuid.UUID('986ad77f-d96d-4ca1-bb64-a35ea130eae3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
