# Generated by Django 2.2 on 2020-05-14 08:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_platfrom', '0003_auto_20200514_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='id',
        ),
        migrations.AddField(
            model_name='song',
            name='song_id',
            field=models.UUIDField(default=uuid.UUID('0f338140-386d-4df8-8e83-a592defd7851'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
